### ISSUE TITLE
Incorrect MOVEJ while parameter Z:= x appears

### ISSUE THREAD

**Issue by dturczynski** [rtaylor02/TRIO_SCARA#1]

**Comment by DoTu619** [comment]
ROBOT(0)
MERGE = ON
TRIGGER
MOVEJ GTAJ ("above_pickup_point") S:= 200 A:= 50 D:= 50
MOVEJ GTAJ ("middle_point_with_load") S:= 200 A:= 50 D:= 50 Z:= 100
MOVEJ GTAJ ("above_end_point") S:= 200 A:= 50 D:= 50


//this code lead to incorrect movement. Movement with MOVEL will work correct.
